# The `broker` component: this host's own Mosquitto, authenticated, serving the
# host's own api and gateway. Sourced by deploy.sh in both phases.

broker_units() {
	echo homescope-mqtt
}

broker_dirs() {
	echo "$CFG_DATA_DIR/mosquitto 0755"
}

# The ACL a production broker gets for homescope, generated for this host:
# the same rules the dev broker carries (deploy/mosquitto/dev/acl).
broker_acl() {
	cat <<-EOF
		# Generated by homescope's deploy.sh from deploy.toml; changes are overwritten.
		user $CFG_MQTT_API_USER
		topic read homescope/+/sensors/+/envelope

		user $CFG_MQTT_GATEWAY_USER
		topic write homescope/$CFG_SITE/#
	EOF
}

# Root phase: both clients' passwords, and the two files the broker reads —
# all podman secrets, so they never sit in a file the homescope user's other
# processes could read, and reach the broker as its own uid.
broker_root() {
	# Labelled as generated: should this host later switch to an external
	# broker, require_secret then treats them as unset and asks for the real
	# ones, instead of the API failing to log in with a local password.
	local secret
	for secret in homescope-mqtt-api homescope-mqtt-gateway; do
		if ! secret_exists "$secret"; then
			log "Generating MQTT password $secret"
			generate_password | secret_put "$secret" --label homescope.generated=true
		fi
	done

	local acl
	acl="$(broker_acl)"
	if [[ "$(secret_value homescope-mqtt-acl 2> /dev/null)" != "$acl" ]]; then
		log "Writing the broker ACL"
		printf '%s\n' "$acl" | secret_put homescope-mqtt-acl
	fi

	# mosquitto_passwd salts every hash, so the file cannot be compared with a
	# regenerated one. Instead the secret carries a fingerprint of what it was
	# built from — users and plaintext passwords — and is rebuilt only when
	# that changes (a site rename, or `homescope secret set mqtt-api`).
	local api_password gateway_password fingerprint
	api_password="$(secret_value homescope-mqtt-api)"
	gateway_password="$(secret_value homescope-mqtt-gateway)"
	fingerprint="$(printf '%s\n' "$CFG_MQTT_API_USER" "$api_password" \
		"$CFG_MQTT_GATEWAY_USER" "$gateway_password" | sha256sum | cut -c1-64)"

	local current
	current="$(homescope_podman secret inspect \
		-f '{{index .Spec.Labels "homescope.source"}}' homescope-mqtt-passwd 2> /dev/null || true)"
	if [[ "$current" != "$fingerprint" ]]; then
		log "Writing the broker password file"
		# Passwords travel on stdin; inside the throwaway container they are
		# argv to mosquitto_passwd, visible only within that container.
		# shellcheck disable=SC2016 # expanded by the container's shell
		printf '%s\n%s\n' "$api_password" "$gateway_password" |
			homescope_podman run --rm -i --entrypoint sh docker.io/eclipse-mosquitto:2-openssl -c '
				read -r api; read -r gateway
				mosquitto_passwd -c -b /tmp/passwd "$1" "$api" 2> /dev/null &&
				mosquitto_passwd -b /tmp/passwd "$2" "$gateway" 2> /dev/null &&
				cat /tmp/passwd' sh "$CFG_MQTT_API_USER" "$CFG_MQTT_GATEWAY_USER" |
			secret_put homescope-mqtt-passwd --label "homescope.source=$fingerprint"
	fi
}

# User phase: the broker's config and its host drop-in.
broker_user() {
	local quadlets="$1"

	cp "$SCRIPT_DIR/mosquitto/mosquitto.conf" "$CONFIG_DIR/mosquitto.conf"
	cp "$SCRIPT_DIR/quadlets/homescope-mqtt.container" "$quadlets/"

	write_dropin "$quadlets" homescope-mqtt <<-EOF
		[Container]
		Volume=$CFG_DATA_DIR/mosquitto:/mosquitto/data
	EOF
}
