# The `gateway` component: the receiver dongle's bridge to MQTT. Sourced by
# deploy.sh in both phases.

gateway_units() {
	echo homescope-gateway
}

gateway_dirs() {
	:
}

# Root phase: serial access for the homescope user, the dongle's stable name,
# and — with an external broker — the operator-provided password.
gateway_root() {
	# The group owning serial devices is distro-specific (Debian: dialout, Arch: uucp).
	local serial_group
	if getent group dialout > /dev/null; then
		serial_group="dialout"
	elif getent group uucp > /dev/null; then
		serial_group="uucp"
	else
		die "No serial group (dialout/uucp) found"
	fi

	# Supplementary groups reach a process only when it starts, and every
	# container inherits them from the user's systemd manager — so a group
	# added after it started needs that manager restarted.
	if ! id -nG "$HOMESCOPE_USER" | tr ' ' '\n' | grep -qx "$serial_group"; then
		usermod -aG "$serial_group" "$HOMESCOPE_USER"
		log "Added $HOMESCOPE_USER to $serial_group; restarting its user manager"
		systemctl restart "user@$(id -u "$HOMESCOPE_USER").service"
		wait_for_user_manager
	fi

	local rule="99-homescope-receiver.rules"
	if ! cmp -s "$SCRIPT_DIR/udev/$rule" "/etc/udev/rules.d/$rule"; then
		log "Installing udev rule $rule"
		cp "$SCRIPT_DIR/udev/$rule" /etc/udev/rules.d/
		udevadm control --reload-rules
		udevadm trigger --subsystem-match=tty
	fi

	if ! $CFG_BROKER_LOCAL; then
		require_secret mqtt-gateway "the password of MQTT user $CFG_MQTT_GATEWAY_USER"
	fi
}

gateway_user() {
	local quadlets="$1"

	cat > "$CONFIG_DIR/gateway.env" <<-EOF
		# Generated by deploy.sh from deploy.toml; changes are overwritten.
		SITE=$CFG_SITE
		MQTT_HOST=$CFG_MQTT_HOST
		MQTT_PORT=$CFG_MQTT_PORT
		MQTT_USERNAME=$CFG_MQTT_GATEWAY_USER
	EOF

	cp "$SCRIPT_DIR/quadlets/homescope-gateway.container" "$quadlets/"

	{
		image_lines "$CFG_IMAGE_GATEWAY"
		broker_dependency
	} | write_dropin "$quadlets" homescope-gateway
}
