apiVersion: 1
datasources:
  - name: TimescaleDB
    type: postgres
    url: homescope-db:5432
    user: grafana
    jsonData:
      database: homescope
      sslmode: disable
    secureJsonData:
      password: ${GRAFANA_DB_PASSWORD}
