apiVersion: 1
datasources:
  - name: TimescaleDB
    uid: timescaledb
    type: postgres
    url: homescope-db:5432
    user: ${GRAFANA_DB_USER}
    editable: false
    jsonData:
      database: homescope
      sslmode: disable
      timescaledb: true
    secureJsonData:
      password: ${GRAFANA_DB_PASSWORD}
