#!/bin/bash
set -e
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
	CREATE ROLE api LOGIN PASSWORD '$API_DB_PASSWORD';
	CREATE ROLE grafana LOGIN PASSWORD '$GRAFANA_DB_PASSWORD';
	CREATE DATABASE homescope OWNER api;
EOSQL
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname homescope <<-EOSQL
	GRANT USAGE ON SCHEMA public TO grafana;
	ALTER DEFAULT PRIVILEGES FOR ROLE api IN SCHEMA public
		GRANT SELECT ON TABLES TO grafana;
EOSQL
