# The part of deploy.sh that runs as the homescope user. Sourced by the
# runuser'd shell together with lib/common.sh and components/*.sh; reads the
# CFG_* variables deploy.sh exported.

# The label every generated drop-in carries. After daemon-reload, deploy checks
# each container unit for it: a drop-in podman ignored would leave, say, the
# database writing into its container layer instead of data_dir — silently.
HOST_CONFIG_MARKER="homescope.host-config=1"

# Writes <unit>.container.d/50-host.conf from stdin, the marker label inserted
# into its first [Container] section.
write_dropin() {
	local quadlets="$1" unit="$2"
	mkdir -p "$quadlets/$unit.container.d"
	{
		echo "# Generated by deploy.sh from /etc/homescope/deploy.toml; changes are overwritten."
		awk -v marker="Label=$HOST_CONFIG_MARKER" '
			{ print }
			/^\[Container\]$/ && !done { print marker; done = 1 }
			END { if (!done) exit 1 }
		'
	} > "$quadlets/$unit.container.d/50-host.conf" ||
		die "drop-in for $unit has no [Container] section"
}

# Image and update policy for homescope's own images. A localhost/ image is a
# local build (a test, or a pinned build loaded by hand): `local` restarts the
# container when that image changes; `registry` polls for a newer one.
image_lines() {
	local image="$1"
	echo "[Container]"
	echo "Image=$image"
	if [[ $image == localhost/* ]]; then
		echo "AutoUpdate=local"
	else
		echo "AutoUpdate=registry"
	fi
}

broker_dependency() {
	if $CFG_BROKER_LOCAL; then
		printf '[Unit]\nAfter=homescope-mqtt.service\nWants=homescope-mqtt.service\n'
	fi
}

desired_units() {
	local component
	for component in $CFG_COMPONENTS; do
		"${component}_units"
	done
}

user_phase() {
	[[ -S "$XDG_RUNTIME_DIR/bus" ]] ||
		die "No user manager for $HOMESCOPE_USER at $XDG_RUNTIME_DIR — linger not active yet?"

	# Everything below reads from the root-staged copy, not the checkout.
	SCRIPT_DIR="$STAGING_DIR"

	mkdir -p "$CONFIG_DIR"
	# 755, not 700: containers that drop privileges (postgres, grafana) reach
	# mounts below this dir as other mapped uids and need traversal. Secrets
	# here are protected by their own 600 mode.
	chmod 755 "$CONFIG_DIR"

	# The desired quadlet set is assembled aside, then synced in one go —
	# --delete is what removes a deselected component's units.
	local quadlets
	quadlets="$(mktemp -d)"
	# EXIT, not RETURN: this phase is its own bash process, and a RETURN trap's
	# rules for which function returns fire it are too subtle to rely on. The
	# path is expanded now: at exit, this function's locals no longer exist.
	# shellcheck disable=SC2064
	trap "rm -rf '$quadlets'" EXIT
	cp "$SCRIPT_DIR/quadlets/homescope.network" "$quadlets/"

	local component
	for component in $CFG_COMPONENTS; do
		"${component}_user" "$quadlets"
	done

	# A unit whose quadlet is about to disappear must stop first; otherwise its
	# container outlives the unit file, running with no unit to manage it.
	local file unit
	for file in "$QUADLET_DIR"/*.container; do
		[[ -e $file ]] || continue
		unit="$(basename "$file" .container)"
		if [[ ! -e "$quadlets/$unit.container" ]]; then
			log "Stopping $unit (no longer part of this host)"
			systemctl --user stop "$unit.service" || true
		fi
	done

	log "Syncing quadlets"
	mkdir -p "$QUADLET_DIR"
	rsync -a --delete --checksum "$quadlets/" "$QUADLET_DIR/"

	local dropin_dir="$HOMESCOPE_DIR/.config/systemd/user/podman-auto-update.timer.d"
	mkdir -p "$dropin_dir"
	cp "$SCRIPT_DIR/systemd/podman-auto-update.timer.d/override.conf" "$dropin_dir/"

	# daemon-reload runs the quadlet generator; it must precede the checks
	# and the restarts.
	systemctl --user daemon-reload
	systemctl --user enable --now --quiet podman-auto-update.timer

	for unit in $(desired_units); do
		systemctl --user cat "$unit.service" 2> /dev/null | grep -q -- "$HOST_CONFIG_MARKER" ||
			die "$unit.service was generated without its host drop-in — is this podman too old for quadlet drop-ins? Not starting it."
	done

	# 'restart' reuses cached images and never contacts a registry; without
	# this pass a deploy would restart services on stale code. Same oneshot the
	# timer fires, auto-rollback included. No-op on a first deploy.
	systemctl --user start podman-auto-update.service

	for unit in $(desired_units); do
		log "(Re)starting $unit"
		if [[ $unit == homescope-gateway ]]; then
			# Fails while the receiver is unplugged; the unit keeps retrying.
			systemctl --user restart "$unit.service" ||
				warn "homescope-gateway did not start — is the receiver plugged in? (sudo homescope logs gateway)"
		else
			systemctl --user restart "$unit.service"
		fi
	done

	log "Done. Check with: sudo homescope status"
}
