[package]
name = "homescope-common"
version = "0.1.0"
edition = "2024"

[features]
default = []
wire = ["dep:crc"]
serde = ["dep:serde", "dep:chrono"]
defmt = ["dep:defmt"]

[dependencies]
chrono = { version = "0.4.45", default-features = false, features = ["serde"], optional = true }
crc = { version = "3.4.0", optional = true }
defmt = { version = "1.1.1", optional = true }
serde = { version = "1.0.228", features = ["derive"], optional = true }
thiserror = { version = "2.0.19", default-features = false }
