FROM rust:1.97-trixie AS chef
ENV SQLX_OFFLINE=true

RUN cargo install cargo-chef
WORKDIR /app

FROM chef AS planner
COPY . .
RUN cargo chef prepare --recipe-path recipe.json

FROM chef AS builder
COPY --from=planner /app/recipe.json recipe.json
RUN cargo chef cook --release -p homescope-api --recipe-path recipe.json
COPY Cargo.toml Cargo.lock ./
COPY gateway ./gateway
COPY common ./common
COPY api ./api

RUN cargo build --release -p homescope-api

FROM debian:trixie-slim
COPY --from=builder /app/target/release/homescope-api /usr/local/bin/homescope-api
ENTRYPOINT ["/usr/local/bin/homescope-api"]
